### ISSUE TITLE
我在8.0手机上显示不出来

### ISSUE THREAD

**Issue by ouluqiang** [fangyuxiong/AndroidPerformance#1]
把引用的sdk版本改成了26，就不能显示了，给了权限也不行
```
android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@7a2e770 -- permission denied for window type 2002
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:808)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:359)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at com.xfy.androidperformance.FPSMoniter.addViewToWindow(FPSMoniter.java:70)
        at com.xfy.androidperformance.FPSMoniter.<init>(FPSMoniter.java:54)
        at com.xfy.androidperformance.FPSMoniter.start(FPSMoniter.java:38)
        at com.xfy.androidperformance.FPSMoniterBuilder.build(FPSMoniterBuilder.java:57)
        at com.xfy.sample.MainActivity$1.onClick(MainActivity.java:41)
        at android.view.View.performClick(View.java:6266)
```

**Comment by NIUDONG2015** [comment]
FPSMoniterBuilder 下的    this.context = context.getApplicationContext(); 上下文应该取activity

**Comment by NIUDONG2015** [comment]
加个高版本的判断

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            type = WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY;
        } else {
            type = WindowManager.LayoutParams.TYPE_SYSTEM_ERROR;
        }

https://blog.csdn.net/stimgo/article/details/100703213
